import { GetDoctorsData, GetServiceData } from '@/app/database/handle_data';
import HomePage from './homepage';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
};

export default async function Page() {
  const doctorsData = await GetDoctorsData();

  const serviceData = await GetServiceData();

  return (
    <HomePage
      doctorsData={doctorsData.message}
      serviceData={serviceData.message}
    />
  );
}
