import type { Metadata } from 'next';
import './globals.css';
import Navigation from './components/navigations';
import { LanguageContextProvider } from './components/use-context';

export const metadata: Metadata = {
  title: 'CTVS Experts',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-full w-full">
        <LanguageContextProvider>
          <Navigation />
          {children}
        </LanguageContextProvider>
      </body>
    </html>
  );
}
