import { Metadata } from "next";
import AllDoctors from "./all-doctors-data";
import { GetServiceData } from "../database/handle_data";

export const metadata: Metadata = {
  title: "Our Services",
  description: "Generated by create next app",
};

export default async function Page() {
  const serviceData = await GetServiceData();

  return <AllDoctors serviceData={serviceData} />; // pass to component
}
