import { Metadata } from 'next';
import AllDoctors from './all-doctors-data';
import { GetDoctorsData, GetServiceData } from '../database/handle_data';

export const metadata: Metadata = {
  title: 'Our Services',
  description: 'Generated by create next app',
};

export default async function Page() {
  const doctorsData = await GetDoctorsData();

  const serviceData = await GetServiceData();

  return (
    <AllDoctors
      doctorsData={doctorsData.message}
      serviceData={serviceData.message}
    />
  ); // pass to component
}
