import { Metadata } from 'next';
import AuthPage from './login-sign-up';

export const metadata: Metadata = {
  title: 'Log in ',
  description: 'Generated by create next app',
};

export default function Page() {
  return <AuthPage />;
}
